### ISSUE TITLE
Links in PDF documentation still point here

### ISSUE THREAD

**Issue by ChrisWeiss** [nextthingco/PocketCHIP-Education#1]
There's a couple of links in the PDF documentation that was linked to in the PocketCHIP I just bought that point to this empty repo. It'd be nice if either the links were updated or there was at least a forwarding readme here.

https://drive.google.com/file/d/1oTK28B52D4qcdlfandG9Xhg-bzgSjaF6/view

**Comment by blinkengus** [comment]
Hi Chris, to the sadness of everyone involved in their creation, the CHIP
and PocketCHIP repos are no longer "ours" to maintain. There are
community-hosted repos here: https://github.com/chip-community as well as a
wiki at http://www.chip-community.org
<http://www.chip-community.org/index.php/Main_Page> and a subreddit here:
https://www.reddit.com/r/ChipCommunity/

**Comment by ChrisWeiss** [comment]
Thanks for responding - I didn't find out about the journey of the PocketCHIP team until after posting this. That is very unfortunate, I'm pretty happy with it and there's not a whole lot of ready-to-play options in that price bracket.
